config/routes.rb
Rails.application.routes.draw do


  get '/'  => 'root#top'
  get 'home/about' => 'root#about'
  root 'root#top'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


  belongs_to :user

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    # flash[:notice] = "Welcome! You have loged in successfully."
  	# user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end


  protected
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
  	@book = Book.new
  	@user = current_user
  	@books = @user.books
  end

  def show
    @book = Book.new
    @book_id = Book.find(params[:id])
    @user = @book_id.user
  end

  def index
  	@book = Book.new
  	@books = Book.all
  	@user = current_user
  end

  def create
  	@book = Book.new(book_params)
  	@books = Book.all
  	@book.user_id = current_user.id
  	@user = current_user
  	if @book.save
  	  redirect_to book_path(@book.id), notice: "Book was successfully created."
  	else render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book_id = Book.find(params[:id])
    @user = @book_id.user
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path
    end
  end

  def correct_user
    @book_id = Book.find(params[:id])
    @user = @book_id.user
    redirect_to books_path unless @user == current_user
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end


end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def top
  end

  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  
  def index
  	@users = User.all
  	@user = User.find(current_user.id)
  	@book = Book.new
  end

  def show
  	@user = User.find(params[:id])
  	@books = @user.books.all
  	@book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end


  private
  
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="sidebar col-md-3">
  <div class="user_info">
    <p id="notice"><%= notice %></p>
  	<h2>User info</h2>
  	<table class="table">
  	  <thead>
  	  	<tr>
  	  	  <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", class: "img-responsive" %>
  	  	</tr>
  	  	<tr>
  	  	  <th>name</th>
  	  	  <th><%= user.name %></th>
  	  	</tr>
  	  	<tr>
  	  	  <th>introduction</th>
  	  	  <th><%= user.introduction %></th>
  	  	</tr>
      </thead>
    </table>
    <p class="row">
      <%= link_to edit_user_path(user.id), class: "edit_user_#{user.id}, btn btn-block btn-default" do %>
        <span class= "glyphicon glyphicon-wrench" area-hidden = "true"></span>
      <% end %>
    </p>
  </div>

  <!-- new book -->
  <div class="new-book">
  	<h2>New book</h2>
  	<%= form_for(book) do |f| %>
  	<p class="row">
  	  <%= f.label :title, "Title" %><br>
  	  <%= f.text_field :title, class: "col-md-12 book_title" %>
  	</p>
  	<p class="row">
  	  <%= f.label :body, "Opinion" %><br>
  	  <%= f.text_area :body, rows:"2", class: "col-md-12 book_body" %>
  	</p>
  	<p class="row">
  	  <%= f.submit "Create Book", class: "btn btn-block btn-primary" %>
  	</p>
  	<% end %>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6">
  	  <h1>Editing Book</h1>
  	  <%= form_for(@book) do |f| %>


      <!-- エラーメッセージ -->
      <% if @book.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
            <%= @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>

  	  <div class="row">
        <p>
  	  	  <%= f.label :title, "Title" %>
  	  	  <%= f.text_field :title, class: "book_title col-md-12" %>
        </p>
  	  </div>
      <p></p>
      <div class="row">
        <p>
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: "book_body col-md-12" %>
        </p>
      </div>
      <p></p>
      <div class="row">
        <p>
          <%= f.submit "Update Book", class: "btn btn-block btn-primary" %>
        </p>
      </div>
        <% end %>
  	</div>
    <div class="col-md-3"></div>
  </div>
  
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>
      <span>|</span>
      <%= link_to "Back", books_path, class: "back" %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">

  	<!-- エラーメッセージ -->
  	<% if @book.errors.any? %>
  	  <div id="error_explanation">
        <div class="alert alert-danger">
  	  	  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  	  	  <ul>
  	  	    <% @book.errors.full_messages.each do |message| %>
  	  	      <li><%= message %></li>
  	  	    <% end %>
  	  	  </ul>
        </div>
  	  </div>
  	<% end %>


  	<!-- 左カラム -->
  	  <%= render 'books/list', book: @book, user: @user %>

  	<!-- 右カラム -->
  	<div class="main-list col-md-9">
  	  <div class="books">
  	  	<h2>Books</h2>
  	  	<table class="table">
  	  	  <thead>
  	  	  	<tr>
  	  	  	  <th class="col-md-1"></th>
              <th class="col-md-2"></th>
  	  	  	  <th class="col-md-4">Title</th>
  	  	  	  <th class="col-md-4">Opinion</th>
  	  	  	  <th class="col-md-1"></th>
  	  	  	</tr>
  	  	  </thead>
  	  	  <% @books.each do |book| %>
  	  	     <tbody>
  	  	       <tr>
  	  	         <td><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", class: "img-responsive" %></td>
                 <td></td>
  	  	         <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
  	  	         <td><%= book.body %></td>
  	  	       </tr>
  	  	     </tbody>
  	  	   <% end %>
  	  	 </table>
  	  </div>
  	</div>
  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    
    <%= render 'books/list', book: @book, user: @user %>

    <!-- 右カラム -->
  	<div class="main-list col-md-9">
  	  <div class="books">
  	  	<h2>Books</h2>
  	  	 <table class="table">
  	  	   <thead>
  	  	   	 <tr>
  	  	   	 	<th class="col-md-1"></th>
              <th class="col-md-2">
  	  	   	 	<th class="col-md-4">Title</th>
  	  	   	 	<th class="col-md-4">Opinion</th>
  	  	   	 	<th class="col-md-1"></th>
  	  	   	 </tr>
  	  	   </thead>
  	  	   <% @books.each do |books| %>
  	  	     <tbody>
  	  	       <tr>
  	  	         <td><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "img-responsive" %></td>
                 <td></td>
  	  	         <td><%= link_to books.title, book_path(books.id), class: "book_#{books.id}" %></td>
  	  	         <td><%= books.body %></td>
  	  	       </tr>
  	  	     </tbody>
  	  	   <% end %>
  	  	 </table>
  	  </div>
  	</div>
  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">


    <!-- メイン部分 -->
    <!-- 左カラム -->
    <%= render 'books/list', book: @book, user: @user %>

    <!-- 右カラム -->
    <div class="main-list col-md-9">
      <div class="book-detail">
      	<h2>Book detail</h2>
      	<table class="table">
      	  <thead>
      	  	<% if @user.id == current_user.id %>
      	  	<tr>
      	  	  <td class="col-md-1">
      	  	  	<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "img-responsive" %>
      	  	  	<%= link_to @user.name, user_path(@user.id), class: "user_#{@user.id}" %></td>
      	  	  <td class="col-md-2"></td>
      	  	  <td class="col-md-2">
      	  	  	<%= @book_id.title %></td>
      	  	  <td class="col-md-2">
      	  	  	<%= @book_id.body %></td>
      	  	  <td class="col-md-2">
      	  	  	<%= link_to "Edit", edit_book_path, class: "btn btn-success btn-sm edit_book_#{@book_id.id}" %></td>
      	  	  <td class="col-md-2">
      	  	  	<%= link_to "Destroy", book_path, method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-danger btn-sm destroy_book_#{@book_id.id}" %></td>
      	  	  <td class="col-md-1"></td>
      	  	</tr>
      	  	<% else %>
      	  	<tr>
      	  	  <td class="col-md-1">
      	  	  	<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg" ,class: "img-responsive" %>
      	  	  	<%= link_to @user.name,user_path(@user.id),class: "user_#{@user.id}" %></td>
      	  	  <td class="col-md-2"></td>
			  <td class="col-md-4"><%= @book_id.title %></td>
			  <td class="col-md-5"><%= @book_id.body %></td>
      	  	</tr>
      	  	<% end %>
      	  </thead>
      	</table>
      </div>
    </div>


  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <!-- nav部分 -->
  <body>
    <header class="navbar navbar-inverse navbar-static-top navbar-custom">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarEexample7">
        <div class="navbar-left">
          <span class="navbar-text">Bookers</span>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          <% else %>
            <li><%= link_to " Home", '/', class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " About", "/home/about", class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to " login", user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
        </ul>
        </div>
      </div>
    </header>


    <%= yield %>
  </body>
</html>

app/views/root/about.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-7">
  	  <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers!</strong></h1>
    </div>
    <div class="col-md-5"></div>
  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/root/top.html.erb
<div class="container">
  <div class="row">

  	<!-- 成功メッセージ -->
  	<p id="notice"><%= notice %></p>

  	<div class="col-md-3">
  	</div>
  	<div class="col-md-6">
  	  <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
  	  <p>
  	  	In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,<br>
      </p>
      <p>
  	  	you can share and exchange your opinions , inpressions , and emotions<br>
      </p>
      <p>
  	  	about varioius books!
  	  </p>

      <!-- SignUp,Signinボタン -->
  	  <div class="btn-wrapper">
  	  	<%= link_to "Log in", new_user_session_path, class: "btn btn-block btn-info sign_in" %>
  	  	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-block btn-success sign_up" %>
  	  </div>
  	</div>
  	<div class="col-md-3">
  	</div>
  </div>
 </div>


 <div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
  	<div class="user_info" class="col-md-3">
  	  <h2>User info</h2>

  	  <%= form_for(@user) do |f| %>

  	  <!-- エラーメッセージ -->
  	  <% if @user.errors.any? %>
  	  <div id="error_explanation">
  	  	<div class="alert alert-danger">
  	      <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
  	      <ul>
  	      	<%= @user.errors.full_messages.each do |message| %>
  	      	  <li><%= message %></li>
  	      	<% end %>
  	      </ul>
  	    </div>
  	  </div>
  	  <% end %>

      <!-- フォーム部分 -->
  	  <div class="row">
  	  	<p>
  	  	  <%= f.label :name, "Name" %>
  	  	  <%= f.text_field :name, class: "name" %>
  	  	</p>
  	  </div>
  	  <div class="row">
  	  	<p>
  	  	  <%= f.label :profile_image, "Image" %>
  	  	  <%= f.attachment_field :profile_image, class: "user_image" %>
  	  	</p>
  	  </div>
  	  <div class="row">
  	  	<p>
  	  	  <%= f.label :introduction, "Introduction" %>
  	  	  <%= f.text_area :introduction, class: "introduction" %>
  	  	</p>
  	  </div>
  	  <div class="row">
  	  	<p>
  	  	  <%= f.submit "Update User", class: "btn btn-sm" %>
        </p>
      </div>
  	  <% end %>

  	</div>

  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  	
    <!-- 左カラム -->
  	  <%= render 'books/list', book: @book, user: @user %>

  	<!-- 右カラム -->
  	<div class="main-list col-md-9">
  	  <div class="books">
  	  	<h2>Users</h2>
  	  	<table class="table">
  	  	  <thead>
  	  	  	<tr>
  	  	  	  <th class="col-md-1">image</th>
              <th class="col-md-2"></th>
  	  	  	  <th class="col-md-6">name</th>
  	  	  	  <th class="col-md-3"></th>
  	  	  	</tr>
  	  	  </thead>
  	  	  <% @users.each do |users| %>
  	  	  <tbody>
  	  	  	<tr>
  	  	  	  <td><%= attachment_image_tag users, :profile_image, format: 'jpeg', fallback: "no_image.jpg", class: "img-responsive" %></td>
              <td></td>
  	  	  	  <td><%= users.name %></td>
  	  	  	  <td><%= link_to "Show", user_path(users.id), class: "user_#{users.id}" %></td>
  	  	  	</tr>
  	  	  </tbody>
  	  	  <% end %>
  	  	</table>
  	  </div>
  	</div>
  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

  	<!-- 左カラム -->
  	  <%= render 'books/list', book: @book, user: @user %>

  	<!-- 右カラム -->
  	<div class="main-list col-md-9">
  	  <div class="books">
  	  	<h2>Books</h2>
  	  	 <table class="table">
  	  	   <thead>
  	  	   	 <tr>
  	  	   	 	<th class="col-md-1"></th>
              <th class="col-md-2"></th>
  	  	   	 	<th class="col-md-4">Title</th>
  	  	   	 	<th class="col-md-4">Opinion</th>
  	  	   	 	<th class="col-md-1"></th>
  	  	   	 </tr>
  	  	   </thead>
  	  	   <% @books.each do |books| %>
  	  	     <tbody>
  	  	       <tr>
  	  	         <td><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "img-responsive" %></td>
                 <td></td>
  	  	         <td><%= link_to books.title,book_path(books.id), class: "book_#{books.id}" %></td>
  	  	         <td><%= books.body %></td>
                 <td></td>
  	  	       </tr>
  	  	     </tbody>
  	  	   <% end %>
  	  	 </table>
  	  </div>
  	</div>
  </div>
</div>


<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6"></div>
  	<div class="col-md-3">
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>